### PR TITLE
Move `commitish` field to Metadata class

### PR DESCRIPTION
**Pull request by vfreex**
This is to fix the following issue introduced by https://github.com/openshift/doozer/pull/202

```
ERROR: failed shell command: doozer --datastore prod --cache-dir ...-version v4.5 --release 202006031359
with rc=1 and output:
[...see full archive #3...]
  File "/home/jenkins/.local/lib/python3.6/site-packages/doozerlib/rpmcfg.py", line 61, in __init__
    self.source_path = self.runtime.resolve_source(self)
  File "/home/jenkins/.local/lib/python3.6/site-packages/doozerlib/runtime.py", line 964, in resolve_source
    if meta.commitish:
AttributeError: 'RPMMetadata' object has no attribute 'commitish'
```

### CODE REVIEW

**Comment by shiywang** [comment]
code LGTM, just curious why we move?

**Comment by vfreex** [comment]
It is a quick fix for https://coreos.slack.com/archives/GDBRP5YJH/p1591191441279000
